# Generated by Django 3.2.4 on 2023-06-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa_per', models.IntegerField()),
                ('correo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('nombre_comercial', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10)),
                ('logo', models.BinaryField()),
                ('lleva_contabilidad', models.BooleanField(default=False)),
                ('firma_electronica', models.BinaryField()),
                ('contrasena_firma_electronica', models.CharField(max_length=255)),
                ('desarrollo', models.BooleanField(default=False)),
                ('licencia', models.CharField(max_length=20, unique=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
